name: Simsara
favicon: null
layout_spectrum: 0.9472674722783267
typography_spectrum: 0.37931
title: 'PR & Communications Agency for Arabic Music'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-38452188-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242020'
    - '#5dfc0a'
    - '#000000'
    - '#240000'
    - '#00ff00'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
